export const cityList = [
    { CityName: "臺北市", CityCode: "TPE", City: "Taipei" },
    { CityName: "新北市", CityCode: "NWT", City: "NewTaipei" },
    { CityName: "基隆市", CityCode: "KEE", City: "Keelung" },
    { CityName: "桃園市", CityCode: "TAO", City: "Taoyuan" },
    { CityName: "新竹縣", CityCode: "HSQ", City: "HsinchuCounty" },
    { CityName: "苗栗縣", CityCode: "MIA", City: "MiaoliCounty" },
    { CityName: "臺中市", CityCode: "TXG", City: "Taichung" },
    { CityName: "南投縣", CityCode: "NAN", City: "NantouCounty" },
    { CityName: "彰化縣", CityCode: "CHA", City: "ChanghuaCounty" },
    { CityName: "雲林縣", CityCode: "YUN", City: "YunlinCounty" },
    { CityName: "嘉義市", CityCode: "CYI", City: "Chiayi" },
    { CityName: "嘉義縣", CityCode: "CYQ", City: "ChiayiCounty" },
    { CityName: "臺南市", CityCode: "TNN", City: "Tainan" },
    { CityName: "高雄市", CityCode: "KHH", City: "Kaohsiung" },
    { CityName: "屏東縣", CityCode: "PIF", City: "PingtungCounty" },
    { CityName: "臺東縣", CityCode: "TTT", City: "TaitungCounty" },
    { CityName: "花蓮縣", CityCode: "HUA", City: "HualienCounty" },
    { CityName: "宜蘭縣", CityCode: "ILA", City: "YilanCounty" },
    { CityName: "澎湖縣", CityCode: "PEN", City: "PenghuCounty" },
    { CityName: "金門縣", CityCode: "KIN", City: "KinmenCounty" },
];

export const bikeCityList = [
    { CityName: "臺北市", CityCode: "TPE", City: "Taipei" },
    { CityName: "新北市", CityCode: "NWT", City: "NewTaipei" },
    { CityName: "新竹市", CityCode: "HSZ", City: "Hsinchu" },
    { CityName: "桃園市", CityCode: "TAO", City: "Taoyuan" },
    { CityName: "苗栗縣", CityCode: "MIA", City: "MiaoliCounty" },
    { CityName: "臺中市", CityCode: "TXG", City: "Taichung" },
    { CityName: "嘉義市", CityCode: "CYI", City: "Chiayi" },
    { CityName: "臺南市", CityCode: "TNN", City: "Tainan" },
    { CityName: "高雄市", CityCode: "KHH", City: "Kaohsiung" },
    { CityName: "屏東縣", CityCode: "PIF", City: "PingtungCounty" },
    { CityName: "金門縣", CityCode: "KIN", City: "KinmenCounty" },
]
